service: service-message-broadcast
app: message-broadcast
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: <REGION>
  #profile: engineering-dev

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource: "arn:aws:sns:<REGION>:<ACCOUNT>:<SNS-TOPIC>"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:<REGION>:<ACCOUNT>:table/<DYNAMO-DB-TABLE>"

# you can define service wide environment variables here
#  environment:
#    variable1: value1
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/broadcast
    events:
      - http:
          path: broadcast
          method: post
    environment: # Function level environment variables
      snsTopicArn: "arn:aws:sns:<REGION>:<ACCOUNT>:<SNS-TOPIC>"
      region: "<REGION>"
      tableName: "<DYNAMO-DB-TABLE>"